language: node_js
node_js:
- '6.1'
cache:
  npm: true
  directories:
  - node_modules/
script: npm run coverage
after_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git config --global user.email "infra@scup.com"
- git config --global user.name "Travis CI"
- rm -rf lib
- npm run build
- bin/commit_lib_files.sh
env:
  global:
    secure: W5mS0uXZT2j605ZX8SiFuV9ImtTFYhqvgu7Wa3JRiCn+oHm5JfevxFYvm7mDyznxPKjhFuP5Krwt2oCYnZ/dtslbR3yAZA64vg6BzLog4EJIeYtXvb/6Q1TNnxzlOF3V4F52ZEwftj5RCOWfnr9fR9g6fzStr01zZYwnt0wt5oQqtde7K4tMrd9EnhBoFJQSX9DbHduH/qQOiAcgydFOwhYSuv1/EVcXaD9ppJk5VXfWwlClPcriwpfgWopRnqtAHHqJ6D8sl4qiCx9zsstRNUEbDz36i8H6G8Eyntd+S3FrigppIWWb2k6PtFRWaePcF8rRyB8h+MN8lQt+5Hs9TBwYMWet3oTsOuA4SxCGk4pu7nz80ehmOssK4aO2dkXPDWeWfty7UqLMbE0OTmzAHxzmwBoKh2Wve6DAnblTOV3uaPUFCh4E1xcUEPPwTl4WtVrPmhf6pRI9cgD1lyzP65lfztoqnqpoQlqf3HUYvP78h5PkmJ1UEDHkS/52IEZ3nleJLPhXdpPKCzLfEj596CchDrm0HhmoVHzoRLGs9NuwKNS4YxyD2AsCnJXvE8GTvuMR+J01T46Jm6n1DIUpFJiNb9pa6BiM3tYxnngDEOQgRk2+uqhdFOGRNL7nzbtwQWoVhPssnRuGkeL/PBX/42ZT65/7g4YWABq7cSbGqtU=
